chore: improve ci workflow, ensure built parser committed, cleanup (#166)
* chore: create npm build run-script
* chore: update npm test to include linting
* chore: add DEVELOPMENT.md
* chore: update README.md
* chore(workflow): check for uncommited changes
* chore: commit build diff (license header & new-lines)
* fix(workflow): setup-node's node-version arg

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -80,15 +80,36 @@ jobs:
 
       - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
         with:
-          node.version: ${{ matrix.node.version }}
+          node-version: ${{ matrix.node.version }}
 
       - name: Environment Information
         run: |
           node --version
           npm --version
 
-      - name: npm install and test
-        run: npm cit
+      - name: npm install
+        run: npm ci
+        env:
+          CI: true
+          NODE_OPTIONS: ${{ matrix.node.options }}
+
+      - name: Build parser
+        run: npm run build
+        env:
+          CI: true
+          NODE_OPTIONS: ${{ matrix.node.options }}
+
+      - name: Check for uncommitted changes
+        run: |
+          if ! git diff --exit-code; then
+            echo ""
+            echo "::error::Detected changes that appear to not be committed."
+            echo "::error::Please run 'npm run build' and commit the built parser."
+            exit 1
+          fi
+
+      - name: npm test
+        run: npm t
         env:
           CI: true
           NODE_OPTIONS: ${{ matrix.node.options }}
